Version update 8.7.1 -> 8.8.2

diff --git a/Beats/Dockerfile_Auditbeat b/Beats/Dockerfile_Auditbeat
--- a/Beats/Dockerfile_Auditbeat
+++ b/Beats/Dockerfile_Auditbeat
@@ -1,7 +1,7 @@
 # © Copyright IBM Corporation 2017, 2023.
 # LICENSE: Apache License, Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0)
 
-#################### Dockerfile for Auditbeat 8.7.1 #############################
+#################### Dockerfile for Auditbeat 8.8.2 #############################
 # Beats is the platform for single-purpose data shippers
 #
 # To build this image, from the directory containing this Dockerfile
@@ -17,7 +17,7 @@ FROM ubuntu:20.04 AS builder
 # The author
 LABEL maintainer="LoZ Open Source Ecosystem (https://www.ibm.com/community/z/usergroups/opensource)"
 
-ARG BEATS_VER=8.7.1
+ARG BEATS_VER=8.8.2
 
 # Set environment variable
 ENV BEATNAME=auditbeat
@@ -86,9 +86,9 @@ RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
  && rustup toolchain install 1.65.0 \
  &&	rustup default 1.65.0 \
 # Install go and download beats source code
- && wget https://go.dev/dl/go1.19.7.linux-s390x.tar.gz \
- && chmod ugo+r go1.19.7.linux-s390x.tar.gz \
- && tar -C /usr/local -xzf go1.19.7.linux-s390x.tar.gz \
+ && wget https://go.dev/dl/go1.19.10.linux-s390x.tar.gz \
+ && chmod ugo+r go1.19.10.linux-s390x.tar.gz \
+ && tar -C /usr/local -xzf go1.19.10.linux-s390x.tar.gz \
  && setfacl -dm u::rwx,g::r,o::r $GOPATH \
  && mkdir -p $GOPATH/src/github.com/elastic  \
  && cd $GOPATH/src/github.com/elastic  \
@@ -126,8 +126,15 @@ ENV BEATNAME=auditbeat
 ENV BEATHOME=/usr/share/$BEATNAME
 ENV PATH=$BEATHOME:$PATH
 
-RUN apt-get update && apt-get install -y libpcap0.8 curl sudo \
- && curl --retry 8 -S -L -O "https://github.com/krallin/tini/releases/download/v0.19.0/tini-s390x" \
+RUN for iter in {1..10}; do \
+        apt-get update -y && \
+        DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends --yes ca-certificates curl gawk libpcap0.8 libcap2-bin xz-utils && \
+        apt-get clean all && \
+        exit_code=0 && break || exit_code=$? && echo "apt-get error: retry $iter in 10s" && sleep 10; \
+    done; \
+    (exit $exit_code)
+
+RUN curl --retry 8 -S -L -O "https://github.com/krallin/tini/releases/download/v0.19.0/tini-s390x" \
  && mv tini-s390x /usr/bin/tini \
  && chmod +x /usr/bin/tini
 
@@ -140,7 +147,7 @@ RUN groupadd --gid 1000 $BEATNAME \
  && useradd -M --uid 1000 --gid 1000 --groups 0 --home /usr/share/$BEATHOME $BEATNAME \
  && passwd -d $BEATNAME
 
-#USER $BEATNAME
+USER 1000
 
 ENV LIBBEAT_MONITORING_CGROUPS_HIERARCHY_OVERRIDE=/
 
