Beats version 9.3.1

diff --git a/Beats/Dockerfile_Heartbeat b/Beats/Dockerfile_Heartbeat
--- a/Beats/Dockerfile_Heartbeat
+++ b/Beats/Dockerfile_Heartbeat
@@ -1,7 +1,7 @@
 # © Copyright IBM Corporation 2017, 2026.
 # LICENSE: Apache License, Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0)
 
-#################### Dockerfile for Heartbeat 9.2.4 #############################
+#################### Dockerfile for Heartbeat 9.3.1 #############################
 # Beats is the platform for single-purpose data shippers
 #
 # To build this image, from the directory containing this Dockerfile
@@ -17,7 +17,7 @@ FROM ubuntu:22.04 AS builder
 # The author
 LABEL maintainer="LoZ Open Source Ecosystem (https://www.ibm.com/community/z/open-source/)"
 
-ARG BEATS_VER=9.2.4
+ARG BEATS_VER=9.3.1
 
 # Set environment variable
 ENV BEATNAME=heartbeat
@@ -25,12 +25,10 @@ ENV BEATHOME=/usr/share/$BEATNAME
 ENV SOURCE_DIR=/tmp/source
 WORKDIR $SOURCE_DIR
 ENV GOPATH=$SOURCE_DIR
-ENV PATH=$PATH:/usr/local/go/bin/:$GOPATH/bin:/usr/local/bin
+ENV PATH=$PATH:/usr/local/go/bin/:$GOPATH/bin:/usr/local/bin:/opt/python3.11/bin
 ENV GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=true
-ENV PYTHON_EXE=python3
-ENV PYTHON_ENV=/tmp/venv3
+ENV PYTHON_EXE=python3.11
 ENV TZ=America/Toronto
-ENV PATCH_URL="https://raw.githubusercontent.com/linux-on-ibm-z/scripts/master/Beats/${BEATS_VER}/patch"
 
 # Install dependencies
 RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
@@ -70,25 +68,14 @@ RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
  && wget https://www.python.org/ftp/python/3.11.4/Python-3.11.4.tgz \
  && tar -xzf Python-3.11.4.tgz \
  && cd Python-3.11.4 \
- && ./configure --prefix=/usr/local --exec-prefix=/usr/local \
- && make \
+ && ./configure --prefix=/opt/python3.11 --enable-optimizations --with-lto \
+ && make -j$(nproc) \
  && make install \
- && /usr/bin/update-alternatives --install /usr/bin/python python /usr/local/bin/python3.11 10 \
- && /usr/bin/update-alternatives --install /usr/bin/python3 python3 /usr/local/bin/python3.11 10 \
- && /usr/bin/update-alternatives --display python3 \
- && python3 -V \
- && cd $SOURCE_DIR \
- && wget https://bootstrap.pypa.io/get-pip.py \
- && python3 get-pip.py \
- && pip3 install wheel -v \
- && pip3 install "cython<3.0.0" pyyaml==6.0.2 --no-build-isolation -v \
- && rm get-pip.py \
- && cd $SOURCE_DIR \
+ && rm -rf Python* \
  && wget -O rustup-init.sh https://sh.rustup.rs \
  && bash rustup-init.sh -y \
  && export PATH=$PATH:$HOME/.cargo/bin \
- && rustup toolchain install 1.76.0 \
- && rustup default 1.76.0 \
+# Install go and download beats source code
  && wget https://go.dev/dl/go1.24.11.linux-s390x.tar.gz \
  && chmod ugo+r go1.24.11.linux-s390x.tar.gz \
  && tar -C /usr/local -xzf go1.24.11.linux-s390x.tar.gz \
@@ -96,8 +83,6 @@ RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
  && mkdir -p $GOPATH/src/github.com/elastic  \
  && cd $GOPATH/src/github.com/elastic  \
  && git clone -b v${BEATS_VER} https://github.com/elastic/beats.git  \
- && cd beats  \
- && curl -sSL ${PATCH_URL}/beats.patch | git apply - || error "beats patch" \
 # Building heartbeat
  && cd $GOPATH/src/github.com/elastic/beats/${BEATNAME} \
  && make \
@@ -107,9 +92,10 @@ RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
 # Setup directory layout
 RUN mkdir -p $BEATHOME \
  && cp $GOPATH/src/github.com/elastic/beats/${BEATNAME}/${BEATNAME} $BEATHOME \
- && cp $GOPATH/src/github.com/elastic/beats/${BEATNAME}/${BEATNAME}.yml $BEATHOME \
+ && cp $GOPATH/src/github.com/elastic/beats/LICENSE.txt $BEATHOME/LICENSE.txt \
+ && cp $GOPATH/src/github.com/elastic/beats/NOTICE.txt  $BEATHOME/NOTICE.txt \
  && cp $GOPATH/src/github.com/elastic/beats/${BEATNAME}/${BEATNAME}.reference.yml $BEATHOME \
- && cp $GOPATH/src/github.com/elastic/beats/${BEATNAME}/fields.yml $BEATHOME/fields.yml \
+ && cp $GOPATH/src/github.com/elastic/beats/${BEATNAME}/fields.yml $BEATHOME \
  && cp -r $GOPATH/src/github.com/elastic/beats/${BEATNAME}/monitors.d $BEATHOME \
  && mkdir -p $BEATHOME/data $BEATHOME/logs \
  && chown -R root:root $BEATHOME \
@@ -118,151 +104,107 @@ RUN mkdir -p $BEATHOME \
  && chmod 0775 $BEATHOME/data $BEATHOME/logs \
  && chmod 0755 $BEATHOME/$BEATNAME
 
-FROM ubuntu:22.04
+FROM docker.elastic.co/ubi9/ubi-minimal
 
 LABEL maintainer="LoZ Open Source Ecosystem (https://www.ibm.com/community/z/open-source/)"
 
 ENV ELASTIC_CONTAINER="true"
 ENV BEATNAME=heartbeat
 ENV BEATHOME=/usr/share/$BEATNAME
-ENV NODE_PATH=$BEATHOME/.node
 ENV PATH=$BEATHOME:$PATH
+ENV GODEBUG=madvdontneed=1
 
 RUN for iter in {1..10}; do \
-        apt-get update -y && \
-        DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends --yes ca-certificates curl gawk libpcap0.8 libcap2-bin xz-utils && \
-        apt-get clean all && \
-        exit_code=0 && break || exit_code=$? && echo "apt-get error: retry $iter in 10s" && sleep 10; \
+        microdnf update -y && \
+        microdnf -y install findutils shadow-utils ca-certificates \
+        gawk libcap xz tar && \
+        microdnf clean all && \
+        exit_code=0 && break || exit_code=$? && echo "microdnf error: retry $iter in 10s" && sleep 10; \
     done; \
     (exit $exit_code)
 
-RUN apt-get update -y && \
-    for iter in {1..10}; do \
-        DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends --yes \
-        libglib2.0-0\
-        libnss3\
-        libnspr4\
-        libatk1.0-0\
-        libatk-bridge2.0-0\
-        libcups2\
-        libdrm2\
-        libdbus-1-3\
-        libxcb1\
-        libxkbcommon0\
-        libx11-6\
-        libxcomposite1\
-        libxdamage1\
-        libxext6\
-        libxfixes3\
-        libxrandr2\
-        libgbm1\
-        libpango-1.0-0\
-        libcairo2\
-        libasound2\
-        libatspi2.0-0\
-        libxshmfence1 \
-        fonts-noto \
-        fonts-noto-cjk && \
-        apt-get clean all && \
-        exit_code=0 && break || exit_code=$? && echo "apt-get error: retry $iter in 10s" && sleep 10; \
-    done; \
-    (exit $exit_code)
-
-RUN echo \
-    $NODE_PATH \
-    $BEATHOME/.config \
-    $BEATHOME/.synthetics \
-    $BEATHOME/.npm \
-    $BEATHOME/.cache \
-    | xargs -IDIR sh -c 'mkdir -p DIR && chmod 0770 DIR'
-
-RUN apt-get update && apt-get install -y libpcap0.8 curl sudo \
- && curl --retry 8 -S -L -O "https://github.com/krallin/tini/releases/download/v0.19.0/tini-s390x" \
+RUN curl --retry 8 -S -L -O "https://github.com/krallin/tini/releases/download/v0.19.0/tini-s390x" \
  && mv tini-s390x /usr/bin/tini \
  && chmod +x /usr/bin/tini
 
 COPY docker-entrypoint /usr/local/bin/docker-entrypoint
 RUN chmod 755 /usr/local/bin/docker-entrypoint
 
+COPY --from=builder /usr/share/$BEATNAME /usr/share/$BEATNAME
+RUN readlink -f /usr/share/$BEATNAME/$BEATNAME | xargs setcap cap_net_raw+eip
+
+RUN mkdir /licenses
+COPY --from=builder /usr/share/$BEATNAME/LICENSE.txt /licenses
+COPY --from=builder /usr/share/$BEATNAME/NOTICE.txt /licenses
+
+RUN groupadd --gid 1000 $BEATNAME \
+ && useradd -M --uid 1000 --gid 1000 --groups 0 --home $BEATHOME $BEATNAME
+
+USER root
+
+# Install the deps as needed by the exact version of playwright elastic synthetics uses
+# We don't use npx playwright install-deps because that could pull a newer version
+# Install additional fonts as well
+RUN for iter in {1..10}; do \
+    microdnf -y update && \
+    microdnf -y install fontconfig freetype cairo glib2 gtk3 pango xorg-x11-fonts-misc xorg-x11-fonts-Type1 \
+    at-spi2-atk atk at-spi2-core alsa-lib cups-libs dbus-libs libdrm mesa-libEGL mesa-libgbm nspr nss libX11 \
+    libX11-xcb libxcb libXcomposite libXdamage libXext libXfixes libXrandr libxkbcommon libxshmfence glib2 \
+    dbus-glib libicu mesa-libGL unzip \
+    findutils shadow-utils ca-certificates gawk libcap xz tar -y && \
+    mkdir -p /usr/share/fonts/google-noto && \
+    curl -L -o NotoSansCJKjp.zip https://github.com/notofonts/noto-cjk/releases/download/Sans2.004/06_NotoSansCJKjp.zip && \
+    unzip NotoSansCJKjp.zip -d /usr/share/fonts/google-noto && \
+    rm -f NotoSansCJKjp.zip && \
+    microdnf -y remove unzip && \
+    curl -LO https://github.com/googlefonts/noto-fonts/raw/main/hinted/ttf/NotoSans/NotoSans-Regular.ttf && \
+    mv NotoSans-Regular.ttf /usr/share/fonts/google-noto && \
+    curl -LO https://github.com/googlefonts/noto-emoji/raw/main/fonts/NotoColorEmoji.ttf && \
+    mv NotoColorEmoji.ttf /usr/share/fonts/google-noto && \
+    fc-cache -fv && \
+    microdnf clean all && \
+    exit_code=0 && break || exit_code=$? && echo "microdnf error: retry $iter in 10s" && sleep 10; \
+done; \
+(exit $exit_code)
+
+ENV NODE_PATH=$BEATHOME/.node
+RUN echo \
+    $NODE_PATH \
+    $BEATHOME/.config \
+    $BEATHOME/.synthetics \
+    $BEATHOME/.npm \
+    $BEATHOME/.cache \
+    | xargs -IDIR sh -c 'mkdir -m 0770 -p DIR && chown -R 1000 DIR'
+
 # Setup synthetics env vars
 ENV ELASTIC_SYNTHETICS_CAPABLE=true
-ENV SUITES_DIR=$BEATHOME/suites
-ENV NODE_VERSION=18.20.7
+ENV TZ=UTC
+ENV NODE_VERSION=22.22.0
 ENV PATH="$NODE_PATH/node/bin:$PATH"
-
 # Install the latest version of @elastic/synthetics forcefully ignoring the previously
 # cached node_modules, heartbeat then calls the global executable to run test suites
 # Setup node
+# Also try to add any deps that were missed earlier in terms of playwright reqs
+# playwright install-deps is kept up to date with additional packages chromium needs
+# beyond the base packages listed above
 RUN cd /usr/share/heartbeat/.node \
   && NODE_DOWNLOAD_URL="https://nodejs.org/download/release/v${NODE_VERSION}/node-v${NODE_VERSION}-linux-s390x.tar.xz" \
   && mkdir -p node \
   && curl ${NODE_DOWNLOAD_URL} | tar -xJ --strip 1 -C node \
-  && chmod ug+rwX -R $NODE_PATH 
-
-ENV PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1
-
-RUN npm i -g --loglevel verbose --engine-strict @elastic/synthetics@stack_release || sh -c 'tail -n +1 /root/.npm/_logs/*' \
   && chmod ug+rwX -R $NODE_PATH
 
-USER root
-# Install the deps as needed by the exact version of playwright elastic synthetics uses
-# Community does not use npx playwright install-deps because that could pull a newer version
-# Install additional fonts as well
-RUN for iter in {1..10}; do \
-    apt-get update && \
-    apt-get install -y --no-install-recommends \
-        fontconfig \
-        libfreetype6 \
-        libcairo2 \
-        libglib2.0-0 \
-        libgtk-3-0 \
-        libpango-1.0-0 \
-        x11-utils \
-        xfonts-base \
-        xfonts-100dpi \
-        at-spi2-core \
-        libatk1.0-0 \
-        libatspi2.0-0 \
-        libasound2 \
-        libcups2 \
-        libdbus-1-3 \
-        libdrm2 \
-        libegl1 \
-        libgbm1 \
-        libnspr4 \
-        libnss3 \
-        libx11-6 \
-        libx11-xcb1 \
-        libxcb1 \
-        libxcomposite1 \
-        libxdamage1 \
-        libxext6 \
-        libxfixes3 \
-        libxrandr2 \
-        libxkbcommon0 \
-        libxshmfence1 \
-        libicu70 \
-        libgl1 \
-        fontconfig \
-        fonts-noto-cjk \
-        fonts-noto-color-emoji && \
-    fc-cache -fv && \
-    apt-get clean && rm -rf /var/lib/apt/lists/* && \
-    exit_code=0 && break || exit_code=$? && echo "apt-get error: retry $iter in 10s" && sleep 10; \
-done; \
-(exit $exit_code)
-
-COPY --from=builder /usr/share/$BEATNAME /usr/share/$BEATNAME
-
-RUN groupadd --gid 1000 $BEATNAME \
- && useradd -M --uid 1000 --gid 1000 --groups 0 --home $BEATHOME $BEATNAME 
-
+# Install synthetics as a regular user, installing npm deps as root doesn't work
+RUN chown -R 1000 $NODE_PATH
 USER 1000
+# If this fails dump the NPM logs
+ENV PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1
+RUN npm i -g --loglevel verbose --production --engine-strict @elastic/synthetics@stack_release || sh -c 'tail -n +1 /root/.npm/_logs/* && exit 1'
+RUN chmod ug+rwX -R $NODE_PATH
 
 ENV LIBBEAT_MONITORING_CGROUPS_HIERARCHY_OVERRIDE=/
 
 WORKDIR $BEATHOME
 ENTRYPOINT ["/usr/bin/tini", "--", "/usr/local/bin/docker-entrypoint"]
-CMD ["-environment", "container"]
+CMD ["--environment", "container"]
 
 #End of Dockerfile
diff --git a/Beats/Dockerfile_Packetbeat b/Beats/Dockerfile_Packetbeat
--- a/Beats/Dockerfile_Packetbeat
+++ b/Beats/Dockerfile_Packetbeat
@@ -1,7 +1,7 @@
 # © Copyright IBM Corporation 2017, 2026.
 # LICENSE: Apache License, Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0)
 
-#################### Dockerfile for Packetbeat 9.2.4 #############################
+#################### Dockerfile for Packetbeat 9.3.1 #############################
 # Beats is the platform for single-purpose data shippers
 #
 # To build this image, from the directory containing this Dockerfile
@@ -17,7 +17,7 @@ FROM ubuntu:22.04 AS builder
 # The author
 LABEL maintainer="LoZ Open Source Ecosystem (https://www.ibm.com/community/z/open-source/)"
 
-ARG BEATS_VER=9.2.4
+ARG BEATS_VER=9.3.1
 
 # Set environment variable
 ENV BEATNAME=packetbeat
@@ -25,12 +25,10 @@ ENV BEATHOME=/usr/share/$BEATNAME
 ENV SOURCE_DIR=/tmp/source
 WORKDIR $SOURCE_DIR
 ENV GOPATH=$SOURCE_DIR
-ENV PATH=$PATH:/usr/local/go/bin/:$GOPATH/bin:/usr/local/bin
+ENV PATH=$PATH:/usr/local/go/bin/:$GOPATH/bin:/usr/local/bin:/opt/python3.11/bin
 ENV GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=true
-ENV PYTHON_EXE=python3
-ENV PYTHON_ENV=/tmp/venv3
+ENV PYTHON_EXE=python3.11
 ENV TZ=America/Toronto
-ENV PATCH_URL="https://raw.githubusercontent.com/linux-on-ibm-z/scripts/master/Beats/${BEATS_VER}/patch"
 
 # Install dependencies
 RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
@@ -70,25 +68,13 @@ RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
  && wget https://www.python.org/ftp/python/3.11.4/Python-3.11.4.tgz \
  && tar -xzf Python-3.11.4.tgz \
  && cd Python-3.11.4 \
- && ./configure --prefix=/usr/local --exec-prefix=/usr/local \
- && make \
+ && ./configure --prefix=/opt/python3.11 --enable-optimizations --with-lto \
+ && make -j$(nproc) \
  && make install \
- && /usr/bin/update-alternatives --install /usr/bin/python python /usr/local/bin/python3.11 10 \
- && /usr/bin/update-alternatives --install /usr/bin/python3 python3 /usr/local/bin/python3.11 10 \
- && /usr/bin/update-alternatives --display python3 \
- && python3 -V \
- && cd $SOURCE_DIR \
- && wget https://bootstrap.pypa.io/get-pip.py \
- && python3 get-pip.py \
- && pip3 install wheel -v \
- && pip3 install "cython<3.0.0" pyyaml==6.0.2 --no-build-isolation -v \
- && rm get-pip.py \
  && rm -rf Python* \
  && wget -O rustup-init.sh https://sh.rustup.rs \
  && bash rustup-init.sh -y \
  && export PATH=$PATH:$HOME/.cargo/bin \
- && rustup toolchain install 1.76.0 \
- && rustup default 1.76.0 \
 # Install go and download beats source code
  && wget https://go.dev/dl/go1.24.11.linux-s390x.tar.gz \
  && chmod ugo+r go1.24.11.linux-s390x.tar.gz \
@@ -97,8 +83,6 @@ RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
  && mkdir -p $GOPATH/src/github.com/elastic  \
  && cd $GOPATH/src/github.com/elastic  \
  && git clone -b v${BEATS_VER} https://github.com/elastic/beats.git  \
- && cd beats  \
- && curl -sSL ${PATCH_URL}/beats.patch | git apply - || error "beats patch" \
 # Building packetbeat
  && cd $GOPATH/src/github.com/elastic/beats/${BEATNAME} \
  && make \
@@ -108,9 +92,10 @@ RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
 # Setup directory layout
 RUN mkdir -p $BEATHOME \
  && cp $GOPATH/src/github.com/elastic/beats/${BEATNAME}/${BEATNAME} $BEATHOME \
- && cp $GOPATH/src/github.com/elastic/beats/${BEATNAME}/${BEATNAME}.yml $BEATHOME \
+ && cp $GOPATH/src/github.com/elastic/beats/LICENSE.txt $BEATHOME/LICENSE.txt \
+ && cp $GOPATH/src/github.com/elastic/beats/NOTICE.txt  $BEATHOME/NOTICE.txt \
  && cp $GOPATH/src/github.com/elastic/beats/${BEATNAME}/${BEATNAME}.reference.yml $BEATHOME \
- && cp $GOPATH/src/github.com/elastic/beats/${BEATNAME}/fields.yml $BEATHOME/fields.yml \
+ && cp $GOPATH/src/github.com/elastic/beats/${BEATNAME}/fields.yml $BEATHOME \
  && cp -r $GOPATH/src/github.com/elastic/beats/${BEATNAME}/build/kibana $BEATHOME \
  && mkdir -p $BEATHOME/data $BEATHOME/logs \
  && chown -R root:root $BEATHOME \
@@ -119,7 +104,7 @@ RUN mkdir -p $BEATHOME \
  && chmod 0775 $BEATHOME/data $BEATHOME/logs \
  && chmod 0755 $BEATHOME/$BEATNAME
 
-FROM ubuntu:22.04
+FROM docker.elastic.co/ubi9/ubi-minimal
 
 LABEL maintainer="LoZ Open Source Ecosystem (https://www.ibm.com/community/z/open-source/)"
 
@@ -127,12 +112,15 @@ ENV ELASTIC_CONTAINER="true"
 ENV BEATNAME=packetbeat
 ENV BEATHOME=/usr/share/$BEATNAME
 ENV PATH=$BEATHOME:$PATH
+ENV GODEBUG=madvdontneed=1
 
 RUN for iter in {1..10}; do \
-        apt-get update -y && \
-        DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends --yes ca-certificates curl gawk libpcap0.8 libcap2-bin xz-utils && \
-        apt-get clean all && \
-        exit_code=0 && break || exit_code=$? && echo "apt-get error: retry $iter in 10s" && sleep 10; \
+        microdnf update -y && \
+        microdnf -y install findutils shadow-utils ca-certificates \
+        gawk libcap libpcap xz tar && \
+        microdnf clean all && \
+        ln -sf /usr/lib64/libpcap.so.1 /usr/lib64/libpcap.so.0.8 && \
+        exit_code=0 && break || exit_code=$? && echo "microdnf error: retry $iter in 10s" && sleep 10; \
     done; \
     (exit $exit_code)
 
@@ -144,10 +132,14 @@ COPY docker-entrypoint /usr/local/bin/docker-entrypoint
 RUN chmod 755 /usr/local/bin/docker-entrypoint
 
 COPY --from=builder /usr/share/$BEATNAME /usr/share/$BEATNAME
+RUN readlink -f /usr/share/$BEATNAME/$BEATNAME | xargs setcap cap_net_raw,cap_net_admin+eip
 
-RUN readlink -f /usr/share/$BEATNAME/$BEATNAME | xargs setcap cap_net_raw,cap_net_admin+eip \
- && groupadd --gid 1000 $BEATNAME \
- && useradd -M --uid 1000 --gid 1000 --groups 0 --home /usr/share/$BEATHOME $BEATNAME
+RUN mkdir /licenses
+COPY --from=builder /usr/share/$BEATNAME/LICENSE.txt /licenses
+COPY --from=builder /usr/share/$BEATNAME/NOTICE.txt /licenses
+
+RUN groupadd --gid 1000 $BEATNAME \
+ && useradd -M --uid 1000 --gid 1000 --groups 0 --home $BEATHOME $BEATNAME
 
 USER 1000
 
@@ -155,6 +147,6 @@ ENV LIBBEAT_MONITORING_CGROUPS_HIERARCHY_OVERRIDE=/
 
 WORKDIR $BEATHOME
 ENTRYPOINT ["/usr/bin/tini", "--", "/usr/local/bin/docker-entrypoint"]
-CMD ["-environment", "container"]
+CMD ["--environment", "container"]
 
 #End of Dockerfile
