use entrypoint script

diff --git a/ApacheStorm/Dockerfile b/ApacheStorm/Dockerfile
--- a/ApacheStorm/Dockerfile
+++ b/ApacheStorm/Dockerfile
@@ -1,4 +1,4 @@
-# © Copyright IBM Corporation 2018, 2019.
+# © Copyright IBM Corporation 2018, 2020.
 # LICENSE: Apache License, Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0)
 
 ########## Dockerfile for Apache Storm version 2.2.0 #########
@@ -10,121 +10,167 @@
 #
 # To build this image, from the directory containing this Dockerfile
 # (assuming that the file is named Dockerfile):
-# docker build -t <image_name> .
+# docker build -t storm .
 #
-# To provide custom configuration for Storm use below command:
-# docker run -d -p <host-port>:8080 --name <container-name> -v /<host_path>/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf -v /<host_path>/storm.yaml:/opt/storm/conf/storm.yaml <image-name>
+# Setting up a minimal Storm cluster.
+# Apache Zookeeper is a must for running a Storm cluster.
+# Build Apache Zookeeper image using dockerfile at https://github.com/linux-on-ibm-z/dockerfile-examples/blob/master/ApacheZooKeeper/Dockerfile
+# docker run -d --restart always --name some-zookeeper zookeeper
 #
-# Run nimbus, supervisor & ui daemons using below command:
-# (assuming that user has modified supervisord.conf & storm.yaml files with the requirements of nimbus, supervisor & ui daemons and started Apache ZooKeeper Server )
-# e.g. docker run -d -p 8080:8080 --name stormtest1 -v /root/test/storm/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf -v /root/test/storm/storm.yaml:/opt/storm/conf/storm.yaml super/storms
+# The Nimbus daemon has to be connected with the Zookeeper.
+# docker run -d --restart always --name some-nimbus --link some-zookeeper:zookeeper storm storm nimbus
+#
+# Start a single Supervisor node.
+# docker run -d --restart always --name supervisor --link some-zookeeper:zookeeper --link some-nimbus:nimbus storm storm supervisor
+#
+# Assuming you have topology.jar, submit a topology to our cluster.
+# docker run --link some-nimbus:nimbus -it --rm -v $(pwd)/topology.jar:/topology.jar storm storm jar /topology.jar org.apache.storm.starter.WordCountTopology topology
+#
+# Start the Storm UI.
+# docker run -d -p 8080:8080 --restart always --name ui --link some-nimbus:nimbus storm storm ui
 #
 # Official website: http://storm.apache.org/
-#
-############################ supervisord.conf ##################################
-# [supervisord]
-# nodaemon=true
-#
-# # Start nimbus daemon
-# [program:nimbus]
-# command=storm nimbus
-# startsecs=5
-# autostart=true
-# autorestart=true
-#
-# # Start supervisor daemon
-# [program:supervisor]
-# command=storm supervisor
-# startsecs=5
-# autostart=true
-# autorestart=true
-#
-# # Start ui daemon
-# [program:ui]
-# command=storm ui
-# startsecs=5
-# autostart=true
-# autorestart=true
-#
-#################################################################################
 
 # Base Image
-FROM s390x/ubuntu:18.04
+FROM s390x/ubuntu:18.04 as builder
 
-# The author
-LABEL maintainer="LoZ Open Source Ecosystem (https://www.ibm.com/developerworks/community/groups/community/lozopensource)"
-
-ENV SOURCE_DIR='/root'
-ENV JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-s390x
-ENV STORM_HOME=/opt/storm
-ENV _JAVA_OPTIONS=-Xmx4096m
-ENV JVM_ARGS="-Xms4096m -Xmx4096m"
-ENV MAVEN_OPTS="-Xms4096m -Xmx8192m -Xss4096k"
-ENV PATH=$JAVA_HOME/bin:$SOURCE_DIR/apache-maven-3.5.4/bin:$PATH:$STORM_HOME/bin
+ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-s390x \
+    PATH=$JAVA_HOME/bin:$PATH \
+    SOURCE_DIR=/tmp/source \
+    LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$SOURCE_DIR/zstd-jni/target/classes/linux/s390x/
 
 WORKDIR $SOURCE_DIR
 
-# Install dependencies
-RUN apt-get update  \
- && apt-get install  -y \
-        ant \
-        curl \
-        git \
-        gnupg2 \
-        gpgv \
-        nodejs \
-        openjdk-8-jdk \
-        python \
-        supervisor \
-        tar \
-        wget \
-
-# Install Maven 3.5.4
+# Install required packages
+RUN apt-get update && apt-get install -y --no-install-recommends \
+    bash \
+    gnupg \
+    procps \
+    git \
+    wget \
+    ca-certificates \
+    openjdk-8-jdk \
+    dirmngr \
+    gcc-7 \
+    curl \
+    g++-7 \
+    make \
+    lbzip2; \
+    rm -rf /var/lib/apt/lists/*; \
+    rm -rf /usr/bin/gcc /usr/bin/g++ /usr/bin/cc \
+ && ln -sf /usr/bin/gcc-7 /usr/bin/gcc \
+ && ln -sf /usr/bin/g++-7 /usr/bin/g++ \
+ && ln -sf /usr/bin/gcc /usr/bin/cc \
+ && mkdir -p /rockdb_contents \
  && cd $SOURCE_DIR \
- && wget https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.5.4/apache-maven-3.5.4-bin.tar.gz \
- && tar -xzf apache-maven-3.5.4-bin.tar.gz \
-
-# Install rvm and nvm
- && cd $HOME \
- && command curl -sSL https://rvm.io/mpapis.asc | gpg2 --import - \
- && command curl -sSL https://rvm.io/pkuczynski.asc | gpg2 --import - \
- && curl -L https://get.rvm.io | bash -s stable --autolibs=enabled && . $HOME/.profile \
- && wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.26.1/install.sh | bash && . $HOME/.bashrc \
-
-# Download and build source code of Apache Storm
- && cd $SOURCE_DIR \
- && git clone https://github.com/apache/storm.git \
- && cd storm/ \
- && git checkout tags/v2.2.0 \
- && mvn clean install -DskipTests \
- && ln -s $STORM_HOME/bin/storm /usr/bin/storm \
-
-# Create binary distribution
- && cd $SOURCE_DIR/storm/storm-dist/binary && mvn package -Dgpg.skip=true \
- && tar -zxf $SOURCE_DIR/storm/storm-dist/binary/final-package/target/apache-storm-2.2.0.tar.gz -C $SOURCE_DIR/ \
- && cp -r $SOURCE_DIR/apache-storm-2.2.0 /opt/storm \
-
-# Clean up the unwanted packages and clear the source directory
+ && echo "deb https://dl.bintray.com/sbt/debian /" |  tee -a /etc/apt/sources.list.d/sbt.list \
+ && apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823 \
+ && apt-get update &&  apt-get install -y  sbt \
+ && git clone https://github.com/luben/zstd-jni.git \
+ && cd zstd-jni && git checkout v1.3.8-2 \
+ && sbt compile test package \
+ #Build and Create Rocksdb Jar
+ && cd $SOURCE_DIR && git clone git://github.com/facebook/rocksdb.git \
+ && cd rocksdb && git checkout v5.18.4 \
+ && sed -i -e "s/-march=native/-march=z196/" build_tools/build_detect_platform \
+ && sed -i -e "s/-momit-leaf-frame-pointer/-DDUMBDUMMY/" Makefile \
+ && PORTABLE=1 make shared_lib && make rocksdbjava \
+ && cd $SOURCE_DIR/rocksdb/java/target \
+ && cp rocksdbjni-5.18.4-linux64.jar  rocksdbjni-5.18.4-linux64.jar.backup \
+ && jar -xf rocksdbjni-5.18.4-linux64.jar \
+ && jar -xf rocksdbjni-5.18.4-linux64.jar \
+ && cp librocksdbjni-linux64.so librocksdbjni-linuxs390x.so \
+ && jar -ufv rocksdbjni-5.18.4-linux64.jar librocksdbjni-linuxs390x.so \
+ && cp rocksdbjni-5.18.4-linux64.jar  rocksdbjni-5.18.4.jar \
+ && mv  $SOURCE_DIR/rocksdb/java/target/rocksdbjni-5.18.4.jar  /rockdb_contents/rocksdbjni-5.18.4.jar \
  && apt-get remove -y \
-        ant \
-        curl \
-        git \
-        gnupg2 \
-        maven \
-        wget \
-
- && apt-get autoremove -y \
+     git \
+     wget \
+     make \
  && apt autoremove -y \
- && apt-get clean \
- && rm -rf /var/lib/apt/lists/* $SOURCE_DIR/storm /root/.m2 $SOURCE_DIR/apache-maven-3.5.4-bin.tar.gz
+ && apt-get clean && rm -rf $SOURCE_DIR/zstd-jni && rm -rf $SOURCE_DIR/rocksdb
 
-# Define mount points for backup of config and logs
-VOLUME ["/opt/storm/logs", "/opt/storm/conf"]
 
-# Port for Apache Storm
-EXPOSE 6700 6701 6702 6703 8080 2181 6627 8080 8000 3772 3773 3774
 
-# Set Entrypoint
-CMD ["/usr/bin/supervisord"]
+#######################################################################
+FROM ubuntu:18.04
+ENV STORM_CONF_DIR=/conf \
+    STORM_DATA_DIR=/data \
+    STORM_LOG_DIR=/logs \
+    JAVA_HOME=/usr/lib/jvm/java-8-openjdk-s390x \
+    PATH=$JAVA_HOME/bin:$PATH \
+    SOURCE_DIR=/tmp/source
 
-# End of Dockerfile
+WORKDIR $SOURCE_DIR
+COPY docker-entrypoint.sh /docker-entrypoint.sh
+#
+# Add a user with an explicit UID/GID and create necessary directories
+RUN set -eux \
+ && groupadd -r storm --gid=1000 \
+ && useradd -r -g storm --uid=1000 storm \
+ && mkdir -p "$STORM_CONF_DIR" "$STORM_DATA_DIR" "$STORM_LOG_DIR" \
+ && chown -R storm:storm "$STORM_CONF_DIR" "$STORM_DATA_DIR" "$STORM_LOG_DIR"``
+
+# Install required packages
+RUN set -eux; \
+     apt-get update; \
+     DEBIAN_FRONTEND=noninteractive \
+     apt-get install -y --no-install-recommends \
+     openjdk-8-jdk \
+     bash \
+     ca-certificates \
+     dirmngr \
+     gosu \
+     gnupg \
+     python \
+     procps \
+     wget \
+     libsnappy-dev \
+     libbz2-dev \
+     libffi-dev \
+     tar; \
+     rm -rf /var/lib/apt/lists/*; \
+# Verify that gosu binary works
+    gosu nobody true
+
+ARG GPG_KEY=79B03D059E628478FC9F1D8B152CAD0C46E87B61
+ARG DISTRO_NAME=apache-storm-2.2.0
+# Download Apache Storm, verify its PGP signature, untar and clean up
+RUN set -eux; \
+    ddist() { \
+        local f="$1"; shift; \
+        local distFile="$1"; shift; \
+        local success=; \
+        local distUrl=; \
+        for distUrl in \
+            'https://www.apache.org/dyn/closer.cgi?action=download&filename=' \
+            https://www-us.apache.org/dist/ \
+                        https://www.apache.org/dist/ \
+            https://archive.apache.org/dist/ \
+        ; do \
+            if wget -q -O "$f" "$distUrl$distFile" && [ -s "$f" ]; then \
+                success=1; \
+                break; \
+            fi; \
+           done; \
+           [ -n "$success" ]; \
+    }; \
+    ddist "$DISTRO_NAME.tar.gz" "storm/$DISTRO_NAME/$DISTRO_NAME.tar.gz" \
+ && ddist "$DISTRO_NAME.tar.gz.asc" "storm/$DISTRO_NAME/$DISTRO_NAME.tar.gz.asc" \
+ && export GNUPGHOME="$(mktemp -d)" \
+ && gpg --keyserver ha.pool.sks-keyservers.net --recv-key "$GPG_KEY" || \
+    gpg --keyserver pgp.mit.edu --recv-keys "$GPG_KEY" || \
+    gpg --keyserver keyserver.pgp.com --recv-keys "$GPG_KEY" \
+ && gpg --batch --verify "$DISTRO_NAME.tar.gz.asc" "$DISTRO_NAME.tar.gz" \
+ && tar -xzf "$DISTRO_NAME.tar.gz" \
+ && rm -rf "$GNUPGHOME" "$DISTRO_NAME.tar.gz" "$DISTRO_NAME.tar.gz.asc" \
+ && chown -R storm:storm "$DISTRO_NAME" \
+ && chmod +x /docker-entrypoint.sh \
+ && apt-get remove -y wget \
+ && apt-get clean && apt autoremove -y
+
+WORKDIR $SOURCE_DIR/$DISTRO_NAME
+COPY --from=builder /rockdb_contents/rocksdbjni-5.18.4.jar  $SOURCE_DIR/$DISTRO_NAME/lib/rocksdbjni-5.18.4.jar
+ENV PATH $PATH:$SOURCE_DIR/$DISTRO_NAME/bin
+
+ENTRYPOINT ["/docker-entrypoint.sh"]
